import {StyleSheet} from 'react-native';
import {widthRef, heightRef} from 'src/config/screenSize';
const styles = StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: 'white',
    paddingHorizontal: 24,
  },
  totalBill: {
    marginBottom: 5 * widthRef,
    marginRight: 8 * heightRef,
  },
  amount: {
    // font-size: 20px;
    // font-weight: 600;
    lineHeight: 64,
    letterSpacing: -0.5,
    // text-align: right;
    // marginRight: 5,
  },
  body: {paddingHorizontal: 0 * widthRef},
  textview: {
    height: 50 * heightRef,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  modal: {
    position: 'absolute',
    bottom: 0,
    flex: 1,
    width: '100%',
    backgroundColor: 'white',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 20 * heightRef,
    paddingBottom: 30 * heightRef,
  },
  modalbtn: {
    height: 168 * heightRef,
    width: 110 * widthRef,
    backgroundColor: '#F5F5F5',
    borderRadius: 20,
    justifyContent: 'center',
    padding: 10,
    marginRight: 10,
    marginBottom: 20,
  },
  modalimg: {
    height: 90 * heightRef,
    width: 90 * widthRef,
    borderRadius: 12,
    alignSelf: 'center',

    marginBottom: 10,
  },
  modalVisible: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    opacity: 0.2,
  },
  topbtn: {
    height: 5 * heightRef,
    width: 80 * widthRef,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    marginBottom: 20 * widthRef,
    alignSelf: 'center',
  },
  card: {
    paddingHorizontal: 20 * widthRef,
    marginVertical: 10,
    marginRight: 0,
    paddingBottom: 15 * heightRef,
    alignItem: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingTop: 15 * heightRef,
    backgroundColor: '#F5F5F5',
  },
  card1: {
    paddingHorizontal: 20 * widthRef,
    marginVertical: 10,
    marginRight: 0,
    paddingBottom: 15 * heightRef,
    alignItem: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingTop: 15 * heightRef,
    backgroundColor: '#1C3078',
  },
  servicesView: {
    paddingVertical: 20,
    flexDirection: 'row',
    backgroundColor: 'black',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    overflow: 'hidden',
    marginRight: 20,
  },
  servicesView1: {
    paddingVertical: 20,
    flexDirection: 'row',
    backgroundColor: 'black',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    overflow: 'hidden',
    marginRight: 20,
  },
  hairCutServices: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  hairCutServices1: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  hairCutText: {
    fontWeight: '400',
    marginRight: 10,
    letterSpacing: -0.5,
    textAlign: 'left',
  },
  hairCutImage: {
    height: 80 * heightRef,
    width: 80 * widthRef,
    borderRadius: 50,
  },
  servicesRupees: {
    textAlign: 'left',
    fontWeight: 'bold',
    fontSize: 14,
    marginTop: -20,
  },
  headerTextAll: {
    textAlign: 'right',
    fontWeight: '600',
    lineHeight: 64,
    letterSpacing: -0.5,
    textDecorationLine: 'underline',
  },
  servicesTime: {
    textAlign: 'left',
  },
  servicesTime1: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  headerText: {
    marginTop: 20,
    fontWeight: '600',
    letterSpacing: -0.5,
    textAlign: 'left',
  },
  headerTextAll: {
    textAlign: 'right',
    fontWeight: '600',
    lineHeight: 64,
    letterSpacing: -0.5,
    textDecorationLine: 'underline',
  },
  headerTextAll: {
    // lineHeight: 64,
    letterSpacing: 0,
    textAlign: 'right',
    textDecorationLine: 'underline',
  },
  textContent: {
    lineHeight: 15,
    letterSpacing: -0.5,
    textAlign: 'left',
    width: 225 * widthRef,
  },
});
export default styles;
