export default {
  LOGIN: {method: 'POST', url: 'auth/login'},
  REGISTER: {method: 'PUT', url: 'auth/signup'},
  SIGNUPOTP: {method: 'POST', url: 'auth/sendOTP'},
  OTPVER: {method: 'POST', url: 'auth/verification'},
  LOGOUT: {method: 'POST', url: 'auth/logout'},
  UPDATEUSER: {method: 'PUT', url: 'users/updateProfile/'},
  FORGET_PASSWORD: {method: 'POST', url: 'auth/forgot'},
  FORGET_OTPVER: {method: 'post', url: 'auth/forgotVerification'},
  FORGET_NEW_PASSWORD: {method: 'PUT', url: 'auth/forgotpassword'},
  BARBERS: {method: 'GET', url: 'barbers/getBarbers'},
  SERVICES: {method: 'GET', url: 'services/getServices'},
  GETFAQS:{method: 'GET', url: 'faqs/getFaqs'},
  BOOKAPPOINT:{method: 'POST', url: 'appointment/bookAppointment/'},
  APPOINTMENTS:{method: 'GET', url: 'appointment/getAppointment/'},
  CHANGEPASS:{method: 'PUT', url: 'users/changePassword/'},
  CHANGENUM:{method: 'PUT', url: 'users/changePhone/'},
  CHANGEOTP:{method: 'PUT', url: 'users/ChangeOTPverification/'},
};
